import "./globals.css";
import Navbar from "./_components/Navbar/Navbar.jsx";
import Footer from "./_components/Footer/Footer.jsx";

export const metadata = {
  title: "Trend Line",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <Navbar />
        <div>
        {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
